# Generated by Django 2.2.13 on 2020-07-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(default=500, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(default=500, verbose_name='Image Width'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='post.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/', verbose_name='image', width_field='image_width'),
        ),
    ]
