# Generated by Django 2.2.13 on 2020-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200703_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/%Y/%m/%d/', verbose_name='image', width_field='image_width'),
        ),
    ]
